//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_MVC_Shop.Contexts
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database_TTTN_0256Entities : DbContext
    {
        public Database_TTTN_0256Entities()
            : base("name=Database_TTTN_0256Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Brand_0256> Brand_0256 { get; set; }
        public DbSet<Category_0256> Category_0256 { get; set; }
        public DbSet<Image_0256> Image_0256 { get; set; }
        public DbSet<ImageType_0256> ImageType_0256 { get; set; }
        public DbSet<Order_0256> Order_0256 { get; set; }
        public DbSet<OrderDetail_0256> OrderDetail_0256 { get; set; }
        public DbSet<Product_0256> Product_0256 { get; set; }
        public DbSet<ProductRating_0256> ProductRating_0256 { get; set; }
        public DbSet<ProductType_0256> ProductType_0256 { get; set; }
        public DbSet<Slider_0256> Slider_0256 { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<User_0256> User_0256 { get; set; }
        public DbSet<UserType_0256> UserType_0256 { get; set; }
        public DbSet<ViewBrand_0256> ViewBrand_0256 { get; set; }
        public DbSet<ViewCategory_0256> ViewCategory_0256 { get; set; }
        public DbSet<ViewProduct_0256> ViewProduct_0256 { get; set; }
        public DbSet<ViewSlider_0256> ViewSlider_0256 { get; set; }
        public DbSet<ViewUser_0256> ViewUser_0256 { get; set; }
        public DbSet<OrderStatus_0256> OrderStatus_0256 { get; set; }
        public DbSet<OrderVoucher_0256> OrderVoucher_0256 { get; set; }
        public DbSet<ViewOrder_0256> ViewOrder_0256 { get; set; }
        public DbSet<ViewOrderDetail_0256> ViewOrderDetail_0256 { get; set; }
    }
}
