//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_MVC_Shop.Contexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserType_0256
    {
        public int id { get; set; }
        public string name { get; set; }
        public string alias { get; set; }
        public Nullable<bool> isPublic { get; set; }
        public Nullable<bool> isTrash { get; set; }
        public string shortDes { get; set; }
    }
}
