//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_MVC_Shop.Contexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewOrder_0256
    {
        public int id { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> voucherSale { get; set; }
        public Nullable<bool> isPublic { get; set; }
        public Nullable<bool> isTrash { get; set; }
        public Nullable<int> statusId { get; set; }
        public string statusName { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string location { get; set; }
        public Nullable<int> totalPrice { get; set; }
    }
}
